server.port=8080

spring.application.name=api-gateway

# Включение автоматического обнаружения сервисов и маршрутизации
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Маршруты
# Маршрут для user-service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Маршрут для notification-service
spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://notification-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notifications/**

# Регистрация в Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Swagger UI от user-service
spring.cloud.gateway.routes[2].id=user-service-swagger
spring.cloud.gateway.routes[2].uri=lb://user-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/user-service/swagger-ui.html, /user-service/webjars/**, /user-service/v3/api-docs

