# === Сервер ===
server.port=8082

# === Kafka Consumer ===
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.missing-topics-fatal=false

# === Почта (SMTP через MailHog) ===
spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.protocol=smtp
#spring.mail.username=test
#spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# === Логирование ===
logging.level.ru.saruat.notification=DEBUG
logging.level.org.springframework.kafka=DEBUG