# === Server Port ===
server.port=8080

# === DataSource ===
spring.datasource.url=jdbc:postgresql://localhost:5434/user_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Kafka Producer ===
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topics.userEvents=user-events

# === Logging ===
logging.level.ru.saruat=DEBUG
logging.level.org.springframework.kafka=DEBUG

# === Spring Boot Actuator  dev - always, prod - when-authorized / never ===
management.endpoint.health.show-details=always
